--PRODUCT



insert into product (id, name, price, img, stock) values (1, 'Pimento - Canned', 11.9, 'https://i1.sndcdn.com/avatars-000625777206-fipj53-t500x500.jpg', 40);
insert into product (id, name, price, img, stock) values (2, 'Halibut - Fletches', 6.26, 'https://i1.sndcdn.com/avatars-000625777206-fipj53-t500x500.jpg', 44);
insert into product (id, name, price, img, stock) values (3, 'Glaze - Clear', 25.97, 'https://i1.sndcdn.com/avatars-000625777206-fipj53-t500x500.jpg', 296);
insert into product (id, name, price, img, stock) values (4, 'Sponge Cake Mix - Chocolate', 11.86, 'https://i1.sndcdn.com/avatars-000625777206-fipj53-t500x500.jpg', 138);
insert into product (id, name, price, img, stock) values (5, 'Easy Off Oven Cleaner', 3.65, 'https://i1.sndcdn.com/avatars-000625777206-fipj53-t500x500.jpg', 99);
insert into product (id, name, price, img, stock) values (6, 'Beef - Rib Roast, Capless', 15.66, 'https://i1.sndcdn.com/avatars-000625777206-fipj53-t500x500.jpg', 449);
insert into product (id, name, price, img, stock) values (7, 'Cleaner - Lime Away', 5.6, 'https://i1.sndcdn.com/avatars-000625777206-fipj53-t500x500.jpg', 52);
insert into product (id, name, price, img, stock) values (8, 'Pepperoni Slices', 22.63, 'https://i1.sndcdn.com/avatars-000625777206-fipj53-t500x500.jpg', 41);
insert into product (id, name, price, img, stock) values (9, 'Soup - Knorr, Veg / Beef', 26.06, 'https://i1.sndcdn.com/avatars-000625777206-fipj53-t500x500.jpg', 382);
insert into product (id, name, price, img, stock) values (10, 'Wine - Vouvray Cuvee Domaine', 21.02, 'https://i1.sndcdn.com/avatars-000625777206-fipj53-t500x500.jpg', 439);
insert into product (id, name, price, img, stock) values (11, 'Beef - Eye Of Round', 5.72, 'https://i1.sndcdn.com/avatars-000625777206-fipj53-t500x500.jpg', 62);
insert into product (id, name, price, img, stock) values (12, 'Grand Marnier', 9.17, 'https://i1.sndcdn.com/avatars-000625777206-fipj53-t500x500.jpg', 341);
insert into product (id, name, price, img, stock) values (13, 'Edible Flower - Mixed', 13.12, 'https://i1.sndcdn.com/avatars-000625777206-fipj53-t500x500.jpg', 359);
insert into product (id, name, price, img, stock) values (14, 'Tea - Apple Green Tea', 20.16, 'https://i1.sndcdn.com/avatars-000625777206-fipj53-t500x500.jpg', 291);
insert into product (id, name, price, img, stock) values (15, 'Beef - Cow Feet Split', 29.76, 'https://i1.sndcdn.com/avatars-000625777206-fipj53-t500x500.jpg', 137);
insert into product (id, name, price, img, stock) values (16, 'Wine - Pinot Noir Stoneleigh', 15.65, 'https://i1.sndcdn.com/avatars-000625777206-fipj53-t500x500.jpg', 154);
insert into product (id, name, price, img, stock) values (17, 'Wine - Balbach Riverside', 10.74, 'https://i1.sndcdn.com/avatars-000625777206-fipj53-t500x500.jpg', 463);
insert into product (id, name, price, img, stock) values (18, 'Coffee Cup 8oz 5338cd', 15.81, 'https://i1.sndcdn.com/avatars-000625777206-fipj53-t500x500.jpg', 98);
insert into product (id, name, price, img, stock) values (19, 'Pork - Belly Fresh', 3.93, 'https://i1.sndcdn.com/avatars-000625777206-fipj53-t500x500.jpg', 167);
insert into product (id, name, price, img, stock) values (20, 'Coffee - Dark Roast', 10.63, 'https://i1.sndcdn.com/avatars-000625777206-fipj53-t500x500.jpg', 340);
insert into product (id, name, price, img, stock) values (21, 'Gherkin - Sour', 27.22, 'https://i1.sndcdn.com/avatars-000625777206-fipj53-t500x500.jpg', 362);
insert into product (id, name, price, img, stock) values (22, 'Asparagus - Green, Fresh', 5.67, 'https://i1.sndcdn.com/avatars-000625777206-fipj53-t500x500.jpg', 388);
insert into product (id, name, price, img, stock) values (23, 'Parasol Pick Stir Stick', 6.67, 'https://i1.sndcdn.com/avatars-000625777206-fipj53-t500x500.jpg', 153);
insert into product (id, name, price, img, stock) values (24, 'Bread - Sour Sticks With Onion', 29.26, 'https://i1.sndcdn.com/avatars-000625777206-fipj53-t500x500.jpg', 422);
insert into product (id, name, price, img, stock) values (25, 'Sauce - Chili', 12.05, 'https://i1.sndcdn.com/avatars-000625777206-fipj53-t500x500.jpg', 259);
insert into product (id, name, price, img, stock) values (26, 'Lid - 10,12,16 Oz', 23.01, 'https://i1.sndcdn.com/avatars-000625777206-fipj53-t500x500.jpg', 45);
insert into product (id, name, price, img, stock) values (27, 'Sweet Pea Sprouts', 7.11, 'https://i1.sndcdn.com/avatars-000625777206-fipj53-t500x500.jpg', 336);
insert into product (id, name, price, img, stock) values (28, 'Cheese - Pont Couvert', 13.79, 'https://i1.sndcdn.com/avatars-000625777206-fipj53-t500x500.jpg', 355);
insert into product (id, name, price, img, stock) values (29, 'Fish - Base, Bouillion', 13.49, 'https://i1.sndcdn.com/avatars-000625777206-fipj53-t500x500.jpg', 171);
insert into product (id, name, price, img, stock) values (30, 'Pike - Frozen Fillet', 22.12, 'https://i1.sndcdn.com/avatars-000625777206-fipj53-t500x500.jpg', 104);
insert into product (id, name, price, img, stock) values (31, 'Glaze - Apricot', 26.51, 'https://i1.sndcdn.com/avatars-000625777206-fipj53-t500x500.jpg', 115);
insert into product (id, name, price, img, stock) values (32, 'Lemon Grass', 9.27, 'https://i1.sndcdn.com/avatars-000625777206-fipj53-t500x500.jpg', 450);
insert into product (id, name, price, img, stock) values (33, 'Puree - Guava', 19.57, 'https://i1.sndcdn.com/avatars-000625777206-fipj53-t500x500.jpg', 206);
insert into product (id, name, price, img, stock) values (34, 'Carrots - Mini Red Organic', 26.54, 'https://i1.sndcdn.com/avatars-000625777206-fipj53-t500x500.jpg', 491);
insert into product (id, name, price, img, stock) values (35, 'Breadfruit', 10.16, 'https://i1.sndcdn.com/avatars-000625777206-fipj53-t500x500.jpg', 40);
insert into product (id, name, price, img, stock) values (36, 'Crackers - Melba Toast', 21.25, 'https://i1.sndcdn.com/avatars-000625777206-fipj53-t500x500.jpg', 7);
insert into product (id, name, price, img, stock) values (37, 'Chocolate - Semi Sweet', 26.18, 'https://i1.sndcdn.com/avatars-000625777206-fipj53-t500x500.jpg', 348);
insert into product (id, name, price, img, stock) values (38, 'Cheese - Provolone', 11.79, 'https://i1.sndcdn.com/avatars-000625777206-fipj53-t500x500.jpg', 111);
insert into product (id, name, price, img, stock) values (39, 'Bread - English Muffin', 16.19, 'https://i1.sndcdn.com/avatars-000625777206-fipj53-t500x500.jpg', 379);
insert into product (id, name, price, img, stock) values (40, 'Wine - Fat Bastard Merlot', 6.8, 'https://i1.sndcdn.com/avatars-000625777206-fipj53-t500x500.jpg', 92);
insert into product (id, name, price, img, stock) values (41, 'Pastry - Chocolate Chip Muffin', 21.29, 'https://i1.sndcdn.com/avatars-000625777206-fipj53-t500x500.jpg', 145);
insert into product (id, name, price, img, stock) values (42, 'Muffin - Mix - Creme Brule 15l', 9.27, 'https://i1.sndcdn.com/avatars-000625777206-fipj53-t500x500.jpg', 324);
insert into product (id, name, price, img, stock) values (43, 'Ice Cream - Super Sandwich', 13.84, 'https://i1.sndcdn.com/avatars-000625777206-fipj53-t500x500.jpg', 402);
insert into product (id, name, price, img, stock) values (44, 'Bread - Assorted Rolls', 6.67, 'https://i1.sndcdn.com/avatars-000625777206-fipj53-t500x500.jpg', 468);
insert into product (id, name, price, img, stock) values (45, 'Ocean Spray - Ruby Red', 3.22, 'https://i1.sndcdn.com/avatars-000625777206-fipj53-t500x500.jpg', 38);
insert into product (id, name, price, img, stock) values (46, 'Beef - Chuck, Boneless', 17.36, 'https://i1.sndcdn.com/avatars-000625777206-fipj53-t500x500.jpg', 258);
insert into product (id, name, price, img, stock) values (47, 'Oysters - Smoked', 27.65, 'https://i1.sndcdn.com/avatars-000625777206-fipj53-t500x500.jpg', 439);
insert into product (id, name, price, img, stock) values (48, 'Compound - Rum', 25.98, 'https://i1.sndcdn.com/avatars-000625777206-fipj53-t500x500.jpg', 162);
insert into product (id, name, price, img, stock) values (49, 'Aspic - Light', 17.82, 'https://i1.sndcdn.com/avatars-000625777206-fipj53-t500x500.jpg', 476);
insert into product (id, name, price, img, stock) values (50, 'Hersey Shakes', 23.31, 'https://i1.sndcdn.com/avatars-000625777206-fipj53-t500x500.jpg', 247);




--PERSON


insert into person (id, names, lastnames, dni, email) values (1, 'Adorne', 'Betteney', 'Jr', 'abetteney0@yale.edu');
insert into person (id, names, lastnames, dni, email) values (2, 'Howie', 'Silvers', 'Sr', 'hsilvers1@edublogs.org');
insert into person (id, names, lastnames, dni, email) values (3, 'Austen', 'Milch', 'II', 'amilch2@trellian.com');
insert into person (id, names, lastnames, dni, email) values (4, 'Averil', 'Meadway', 'III', 'ameadway3@yale.edu');
insert into person (id, names, lastnames, dni, email) values (5, 'Lorelei', 'Airth', 'II', 'lairth4@cafepress.com');
insert into person (id, names, lastnames, dni, email) values (6, 'Rhodia', 'Gerhardt', 'Sr', 'rgerhardt5@unc.edu');
insert into person (id, names, lastnames, dni, email) values (7, 'Cherri', 'Beamont', 'IV', 'cbeamont6@paypal.com');
insert into person (id, names, lastnames, dni, email) values (8, 'Julietta', 'Ramsted', 'Jr', 'jramsted7@comcast.net');
insert into person (id, names, lastnames, dni, email) values (9, 'Minda', 'Pilley', 'II', 'mpilley8@wp.com');
insert into person (id, names, lastnames, dni, email) values (10, 'Hailey', 'Eastam', 'Jr', 'heastam9@sohu.com');
insert into person (id, names, lastnames, dni, email) values (11, 'Rolland', 'Firth', 'Sr', 'rfirtha@sbwire.com');
insert into person (id, names, lastnames, dni, email) values (12, 'Agnese', 'Caddell', 'III', 'acaddellb@ustream.tv');
insert into person (id, names, lastnames, dni, email) values (13, 'Pryce', 'Montilla', 'Sr', 'pmontillac@tripod.com');
insert into person (id, names, lastnames, dni, email) values (14, 'Niels', 'O''Carmody', 'II', 'nocarmodyd@4shared.com');
insert into person (id, names, lastnames, dni, email) values (15, 'Maitilde', 'Mum', 'IV', 'mmume@fastcompany.com');
insert into person (id, names, lastnames, dni, email) values (16, 'Aurelea', 'Minichillo', 'Jr', 'aminichillof@paginegialle.it');
insert into person (id, names, lastnames, dni, email) values (17, 'Helene', 'Sammut', 'IV', 'hsammutg@instagram.com');
insert into person (id, names, lastnames, dni, email) values (18, 'Donny', 'Allawy', 'II', 'dallawyh@wp.com');
insert into person (id, names, lastnames, dni, email) values (19, 'Ursula', 'Amor', 'III', 'uamori@paypal.com');
insert into person (id, names, lastnames, dni, email) values (20, 'Robenia', 'Frears', 'II', 'rfrearsj@ebay.co.uk');
insert into person (id, names, lastnames, dni, email) values (21, 'Annnora', 'Van Geffen', 'II', 'avangeffenk@topsy.com');
insert into person (id, names, lastnames, dni, email) values (22, 'Dallas', 'Glas', 'III', 'dglasl@timesonline.co.uk');
insert into person (id, names, lastnames, dni, email) values (23, 'Rand', 'Whitlow', 'II', 'rwhitlowm@imdb.com');
insert into person (id, names, lastnames, dni, email) values (24, 'Ottilie', 'Pumfrey', 'Jr', 'opumfreyn@usgs.gov');
insert into person (id, names, lastnames, dni, email) values (25, 'Barnie', 'Ballach', 'IV', 'bballacho@google.nl');
insert into person (id, names, lastnames, dni, email) values (26, 'Bette-ann', 'Bowley', 'III', 'bbowleyp@imageshack.us');
insert into person (id, names, lastnames, dni, email) values (27, 'Myrle', 'Palumbo', 'Jr', 'mpalumboq@un.org');
insert into person (id, names, lastnames, dni, email) values (28, 'Maura', 'Templeton', 'II', 'mtempletonr@army.mil');
insert into person (id, names, lastnames, dni, email) values (29, 'Shelby', 'Dederich', 'Jr', 'sdederichs@behance.net');
insert into person (id, names, lastnames, dni, email) values (30, 'Barbabas', 'O''Flynn', 'II', 'boflynnt@berkeley.edu');
insert into person (id, names, lastnames, dni, email) values (31, 'Serena', 'Oldacres', 'Jr', 'soldacresu@un.org');
insert into person (id, names, lastnames, dni, email) values (32, 'Janene', 'Burchall', 'Jr', 'jburchallv@moonfruit.com');
insert into person (id, names, lastnames, dni, email) values (33, 'Leone', 'Rankin', 'IV', 'lrankinw@tripod.com');
insert into person (id, names, lastnames, dni, email) values (34, 'Frannie', 'Kinnie', 'II', 'fkinniex@washingtonpost.com');
insert into person (id, names, lastnames, dni, email) values (35, 'Anna-diana', 'Bore', 'Jr', 'aborey@theguardian.com');
insert into person (id, names, lastnames, dni, email) values (36, 'Darb', 'Lillywhite', 'Sr', 'dlillywhitez@usatoday.com');
insert into person (id, names, lastnames, dni, email) values (37, 'Donni', 'Sandercock', 'Jr', 'dsandercock10@opensource.org');
insert into person (id, names, lastnames, dni, email) values (38, 'Kial', 'Frossell', 'Sr', 'kfrossell11@howstuffworks.com');
insert into person (id, names, lastnames, dni, email) values (39, 'Matthiew', 'Corbie', 'IV', 'mcorbie12@apple.com');
insert into person (id, names, lastnames, dni, email) values (40, 'Mathias', 'Tesauro', 'Sr', 'mtesauro13@wikia.com');
insert into person (id, names, lastnames, dni, email) values (41, 'Rodie', 'Peedell', 'III', 'rpeedell14@aboutads.info');
insert into person (id, names, lastnames, dni, email) values (42, 'Genevieve', 'Josefsson', 'Jr', 'gjosefsson15@jalbum.net');
insert into person (id, names, lastnames, dni, email) values (43, 'Herbie', 'Vedekhin', 'II', 'hvedekhin16@japanpost.jp');
insert into person (id, names, lastnames, dni, email) values (44, 'Felipa', 'Sambiedge', 'III', 'fsambiedge17@shop-pro.jp');
insert into person (id, names, lastnames, dni, email) values (45, 'Mersey', 'Archbald', 'Jr', 'marchbald18@unc.edu');
insert into person (id, names, lastnames, dni, email) values (46, 'Frazer', 'Sebright', 'Jr', 'fsebright19@redcross.org');
insert into person (id, names, lastnames, dni, email) values (47, 'Corabella', 'Astle', 'Jr', 'castle1a@e-recht24.de');
insert into person (id, names, lastnames, dni, email) values (48, 'Murvyn', 'Steer', 'III', 'msteer1b@mozilla.com');
insert into person (id, names, lastnames, dni, email) values (49, 'Adrea', 'Oleksiak', 'III', 'aoleksiak1c@comcast.net');
insert into person (id, names, lastnames, dni, email) values (50, 'Libbie', 'Mattheeuw', 'Jr', 'lmattheeuw1d@earthlink.net');
insert into person (id, names, lastnames, dni, email) values (51, 'Ole', 'Walework', 'III', 'owalework1e@ycombinator.com');
insert into person (id, names, lastnames, dni, email) values (52, 'Annaliese', 'Jeandet', 'II', 'ajeandet1f@shop-pro.jp');
insert into person (id, names, lastnames, dni, email) values (53, 'Donelle', 'Mulligan', 'Sr', 'dmulligan1g@zimbio.com');
insert into person (id, names, lastnames, dni, email) values (54, 'Mellie', 'Hefford', 'IV', 'mhefford1h@t.co');
insert into person (id, names, lastnames, dni, email) values (55, 'Lexy', 'Kupis', 'III', 'lkupis1i@dedecms.com');
insert into person (id, names, lastnames, dni, email) values (56, 'Vonni', 'Hargess', 'III', 'vhargess1j@omniture.com');
insert into person (id, names, lastnames, dni, email) values (57, 'Savina', 'Petrushanko', 'II', 'spetrushanko1k@nytimes.com');
insert into person (id, names, lastnames, dni, email) values (58, 'Darby', 'Floweth', 'IV', 'dfloweth1l@de.vu');
insert into person (id, names, lastnames, dni, email) values (59, 'Tobi', 'Bycraft', 'Sr', 'tbycraft1m@exblog.jp');
insert into person (id, names, lastnames, dni, email) values (60, 'Stoddard', 'Llewhellin', 'IV', 'sllewhellin1n@sphinn.com');
insert into person (id, names, lastnames, dni, email) values (61, 'Sasha', 'Searjeant', 'Jr', 'ssearjeant1o@ihg.com');
insert into person (id, names, lastnames, dni, email) values (62, 'Lazaro', 'Witton', 'Sr', 'lwitton1p@weibo.com');
insert into person (id, names, lastnames, dni, email) values (63, 'Dorothee', 'Learman', 'Jr', 'dlearman1q@wiley.com');
insert into person (id, names, lastnames, dni, email) values (64, 'Victoria', 'Mollnar', 'Sr', 'vmollnar1r@house.gov');
insert into person (id, names, lastnames, dni, email) values (65, 'Hadleigh', 'Gilhouley', 'II', 'hgilhouley1s@squarespace.com');
insert into person (id, names, lastnames, dni, email) values (66, 'Siobhan', 'Laurencot', 'Sr', 'slaurencot1t@cbsnews.com');
insert into person (id, names, lastnames, dni, email) values (67, 'Bessie', 'Adlem', 'Jr', 'badlem1u@bravesites.com');
insert into person (id, names, lastnames, dni, email) values (68, 'Bobbee', 'Souter', 'II', 'bsouter1v@hhs.gov');
insert into person (id, names, lastnames, dni, email) values (69, 'Gweneth', 'Willoughby', 'III', 'gwilloughby1w@example.com');
insert into person (id, names, lastnames, dni, email) values (70, 'Brandyn', 'Norvell', 'II', 'bnorvell1x@gnu.org');
insert into person (id, names, lastnames, dni, email) values (71, 'Ursa', 'Margrett', 'II', 'umargrett1y@google.es');
insert into person (id, names, lastnames, dni, email) values (72, 'Marion', 'Langridge', 'II', 'mlangridge1z@adobe.com');
insert into person (id, names, lastnames, dni, email) values (73, 'Evelina', 'Eltone', 'III', 'eeltone20@ucla.edu');
insert into person (id, names, lastnames, dni, email) values (74, 'Shanie', 'Thacke', 'Sr', 'sthacke21@mysql.com');
insert into person (id, names, lastnames, dni, email) values (75, 'Gates', 'MacNamee', 'IV', 'gmacnamee22@gravatar.com');
insert into person (id, names, lastnames, dni, email) values (76, 'Benton', 'Spurdens', 'IV', 'bspurdens23@mtv.com');
insert into person (id, names, lastnames, dni, email) values (77, 'Abbie', 'Bydaway', 'Sr', 'abydaway24@1und1.de');
insert into person (id, names, lastnames, dni, email) values (78, 'Randi', 'Ducarne', 'II', 'rducarne25@foxnews.com');
insert into person (id, names, lastnames, dni, email) values (79, 'Cynthia', 'McCaskill', 'III', 'cmccaskill26@rediff.com');
insert into person (id, names, lastnames, dni, email) values (80, 'Selene', 'Favell', 'IV', 'sfavell27@latimes.com');
insert into person (id, names, lastnames, dni, email) values (81, 'Flori', 'Killik', 'IV', 'fkillik28@infoseek.co.jp');
insert into person (id, names, lastnames, dni, email) values (82, 'Frazer', 'Pyatt', 'Sr', 'fpyatt29@go.com');
insert into person (id, names, lastnames, dni, email) values (83, 'Cal', 'Tyce', 'IV', 'ctyce2a@thetimes.co.uk');
insert into person (id, names, lastnames, dni, email) values (84, 'Juanita', 'Beetles', 'Jr', 'jbeetles2b@yandex.ru');
insert into person (id, names, lastnames, dni, email) values (85, 'Leroy', 'McMillam', 'Sr', 'lmcmillam2c@naver.com');
insert into person (id, names, lastnames, dni, email) values (86, 'Philippine', 'Dalgleish', 'IV', 'pdalgleish2d@shareasale.com');
insert into person (id, names, lastnames, dni, email) values (87, 'Koressa', 'Spoure', 'II', 'kspoure2e@wikia.com');
insert into person (id, names, lastnames, dni, email) values (88, 'Xena', 'Bartomeu', 'IV', 'xbartomeu2f@usatoday.com');
insert into person (id, names, lastnames, dni, email) values (89, 'Clerc', 'Freeman', 'Jr', 'cfreeman2g@amazon.co.uk');
insert into person (id, names, lastnames, dni, email) values (90, 'Inna', 'Weedenburg', 'III', 'iweedenburg2h@theguardian.com');
insert into person (id, names, lastnames, dni, email) values (91, 'Rollo', 'Cuxson', 'II', 'rcuxson2i@cocolog-nifty.com');
insert into person (id, names, lastnames, dni, email) values (92, 'Lloyd', 'Salmond', 'II', 'lsalmond2j@yahoo.com');
insert into person (id, names, lastnames, dni, email) values (93, 'Welbie', 'Eisikowitch', 'II', 'weisikowitch2k@theglobeandmail.com');
insert into person (id, names, lastnames, dni, email) values (94, 'Thoma', 'Gymlett', 'III', 'tgymlett2l@privacy.gov.au');
insert into person (id, names, lastnames, dni, email) values (95, 'Quillan', 'Slafford', 'III', 'qslafford2m@chronoengine.com');
insert into person (id, names, lastnames, dni, email) values (96, 'Arron', 'Geaves', 'II', 'ageaves2n@whitehouse.gov');
insert into person (id, names, lastnames, dni, email) values (97, 'Devi', 'Lequeux', 'II', 'dlequeux2o@canalblog.com');
insert into person (id, names, lastnames, dni, email) values (98, 'Kate', 'Sieve', 'III', 'ksieve2p@google.com.au');
insert into person (id, names, lastnames, dni, email) values (99, 'Waverley', 'Varley', 'Sr', 'wvarley2q@wikia.com');
insert into person (id, names, lastnames, dni, email) values (100, 'Claybourne', 'Brackenbury', 'Jr', 'cbrackenbury2r@loc.gov');